superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from superheroes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('update/<int:hero_id>/', views.update, name='update'),
    path('delete/<int:hero_id>/', views.delete, name='delete'),
    path('index/', views.index, name='return'),
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name
        

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Superhero

def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes' : all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego,primary_ability=primary,secondary_ability=secondary,catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request,'superheroes/create.html')

def update(request, hero_id):
    update_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'update_hero': update_hero
    }
    if request.method == "POST":
        update_hero.name = request.POST.get('name')
        update_hero.alter_ego = request.POST.get('alter_ego')
        update_hero.primary_ability = request.POST.get('primary_ability')
        update_hero.secondary_ability = request.POST.get('secondary_ability')
        update_hero.catch_phrase = request.POST.get('catch_phrase')
        update_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request,'superheroes/update.html',context)
        
def delete(request,hero_id):
    Superhero.objects.filter(pk= hero_id).delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
    {% load static %}
    <img src="{% static '/Superhero-logos.jpg/' %}" alt="Superhero-logos">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}">
    
</head>
<body>
    <div class="content">
        <div class="container">
    <form action="{% url 'superheroes:create'%}" method="post">
        {%csrf_token%}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form>
        <br>
        <a class="btn btn-success btn-sm" href="{% url 'superheroes:return' %}">Return to List</a>


        </div>
    </div>
    
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero detail</title>
    {% load static %}
    <img src="{% static '/Superhero-logos.jpg/' %}" alt="Superhero-logos">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}">
</head>
<body>
    <div class="content_a">
        <div class="container">
    <h1><h1>Details About: {{single_hero.name}}</h1>
    <h3>Super Hero Name: {{single_hero.name}} </h3><br>
    <h3>Alter Ego: {{single_hero.alter_ego}}</h3><br>
    <h3>Primary Ability: {{single_hero.primary_ability}}</h3><br>
    <h3>Secondary Ability: {{single_hero.secondary_ability}}</h3><br>
    <h3>Catch Phrase: {{single_hero.catch_phrase}}</h3><br>

    <a class="btn btn-success btn-sm" href="{% url 'superheroes:update' single_hero.id %}">Update Details</a>
    <br>
    <a class="btn btn-success btn-sm" href="{% url 'superheroes:delete' single_hero.id %}">Delete Hero</a>
    <br>
    <a class="btn btn-success btn-sm" href="{% url 'superheroes:return' %}">Return to List</a>
        </div>
    </div>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
    {% load static %}
    <img src="{% static '/Iron-Man.jpg/' %}" alt="Iron-man">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}">
    
</head>
<body>
    <main>
        <div class="content">
            <div class="container">
            <div class="row">
        <h1> List of Heroes</h1>
        <ul style="list-style: none;">
            {% for hero in all_heroes %}<br>
            <li><h2>{{hero.name}} </h2> <h5><a class="button" href="{% url 'superheroes:detail' hero.id %}"><br>Click For Heroes Details</a></h5></li>
            {% endfor %}
            <br>
            <a href="{% url 'superheroes:create'%}">Add Someone New</a>
        </ul>
        </div>



    </main>

</body>
</html>

superhero_project/superheroes/templates/superheroes/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Hero Attribrutes</title>
</head>
<body>
    <form action="{% url 'superheroes:update' update_hero.id%}" method="post">
        {%csrf_token%}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary_ability" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary_ability" id="secondary"><br />
        Catchphrase: <input type="text" name="catch_phrase" id="catchphrase"><br />
        <input type="submit" value="Update!">

    </form>
    
</body>
</html>